name: Build, Push, and Test

on:
  pull_request:
  push:
    branches:
      - main
      - release/*
    tags: '*'
  release:
    types:
      - created

jobs:
  build:
    name: Build and Push the Docker Images
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      dockerfile: docker/Dockerfile
      context: docker

    runs-on: ubuntu-latest
    steps:
      - name: Compute Tag
        uses: actions/github-script@v6
        id: compute-tag
        with:
          result-encoding: string
          script: |
            if (context.eventName === "pull_request") {
              return "pr-" + context.issue.number;
            }
            if (context.eventName === "push") {
              if (context.ref.startsWith("refs/tags/")) {
                return context.ref.slice(10);
              }
              if (context.ref === "refs/heads/main") {
                return "latest";
              }
            }
            return "FALSE";

      - uses: actions/checkout@v2

      -
        name: Docker Login
        id: docker-login
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.compute-tag.outputs.result != 'FALSE' }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      -
        name: Install Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          version: latest

      -
        name: Build Image and Push to GitHub Container Registry and DockerHub
        uses: docker/build-push-action@v2
        if: ${{ steps.compute-tag.outputs.result != 'FALSE' }}
        with:
          context: docker
          file: docker/Dockerfile
          tags: |
            ls1tum/eos:${{ steps.compute-tag.outputs.result }}
            ghcr.io/ls1intum/eos:${{ steps.compute-tag.outputs.result }}
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ !startsWith(steps.compute-tag.outputs.result, 'pr-') }}

  test-solution:
    name: Run Tests for Solution
    needs: buildx
    runs-on: ubuntu-latest
    container: ls1tum/eos:0.0.5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy solution to example/tests/assignment
        run: |
          mkdir -p example/tests/assignment
          cp -r example/solution/* example/tests/assignment/

      - name: Run Gradle Tests
        working-directory: example/tests
        run: ./gradlew test

  test-template:
    name: Run Tests for Template
    needs: buildx
    runs-on: ubuntu-latest
    container: ls1tum/eos:0.0.5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy template to example/tests/assignment
        run: |
          mkdir -p example/tests/assignment
          cp -r example/template/* example/tests/assignment/

      - name: Run Gradle Tests
        working-directory: example/tests
        run: |
          if ./gradlew test; then
            echo "❌ Tests unexpectedly passed!"
            exit 1
          else
            echo "✅ Tests failed as expected."
          fi
