name: Test Example

on:
  pull_request:
  push:
    branches:
      - main
      - release/*
    tags: "*"
  release:
    types:
      - created

jobs:
  test-solution:
    name: Run Tests for Solution
    runs-on: ubuntu-latest
    container: ls1tum/eos:0.0.5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy solution to example/tests/assignment
        run: |
          mkdir -p example/tests/assignment
          cp -r example/solution/* example/tests/assignment/

      - name: Run Gradle Tests
        working-directory: example/tests
        run: ./gradlew test

  test-template:
    name: Run Tests for Template
    runs-on: ubuntu-latest
    container: ls1tum/eos:0.0.5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy template to example/tests/assignment
        run: |
          mkdir -p example/tests/assignment
          cp -r example/template/* example/tests/assignment/

      - name: Run Gradle Tests
        working-directory: example/tests
        run: |
          if ./gradlew test; then
            echo "❌ Tests unexpectedly passed!"
            exit 1
          else
            echo "✅ Tests failed as expected."
          fi
